### ISSUE TITLE
mind if i use this template commercially?

### ISSUE THREAD

**Issue by Mootbing** [goodform-ai/expo-tensorflow-pose#1]
will give attribution.

**Comment by julian-hecker** [comment]
@Mootbing Hi there, I'm glad you find this project interesting! Feel free to use this template, but please attribute to [GoodForm AI](https://github.com/goodform-ai). I will transfer this project to be managed there.

**Comment by julian-hecker** [comment]
@Mootbing Also please test this on an Android device before releasing anything. Last I checked, I there were some issues running it on Android.

**Comment by Mootbing** [comment]
Thank you! Amazing work.
